### ISSUE TITLE
Registry for catalog fields

### ISSUE THREAD

**Issue by acbegen** [moq-wg/catalog-format#26]
I suggest creating an IANA registry for catalog fields with values auto-populated from Section 3.2.

**Comment by wilaw** [comment]
What is the point of shifting the catalog fields definitions to IANA? IANA is useful for ensuring global uniqueness. If a single specification defines the catalog format, then that spec if a much more efficient and natural place to define the fields used by that format.

**Comment by acbegen** [comment]
If we end up needing new fields (which we certainly will), we don't need a revised RFC. The fields table can be amended/expanded in a number of ways.
